---
- name: Install required system packages
  package:
    name: chrony
    state: present

- name: Ensure chrony service is running
  systemd:
    name: chrony
    state: started
    enabled: true

