---
- name: Reload systemd
  command: systemctl daemon-reexec

- name: Reload sysctl
  command: sysctl -p

- name: Rebuild GRUB configuration
  command: update-grub
# Add handler for systemd reload
- name: Reload systemd
  command: systemctl daemon-reload
